
/*CRIAÇÃO DATABASE*/
IF NOT EXISTS (SELECT * FROM sys.databases WHERE NAME = 'DESAFIO-RADIX')
	BEGIN 
		CREATE DATABASE [DESAFIO-RADIX]
	END
GO;

USE [DESAFIO-RADIX]


/*CRIAÇÃO SCHEMA STAGE*/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE NAME = 'stage')
	BEGIN 
		EXEC('CREATE SCHEMA stage')
	END 
GO;

/*CRIAÇÃO SCHEMA DW*/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE NAME = 'dw')
	BEGIN 
		EXEC('CREATE SCHEMA dw')
	END 
GO

