

/*CRIAÇÃO TABELA CONFIRMADOS NO SCHEMA STAGE*/

CREATE TABLE stage.confirmados
(
  ESTADO VARCHAR(250)
, PAIS VARCHAR(250)
, LATITUDE VARCHAR(20)
, LONGITUDE VARCHAR(20)
, DATA DATE
, QTD_CONFIRMADOS_ACUMULADOS INT
)
GO


/*CRIAÇÃO TABELA MORTES NO SCHEMA STAGE*/
CREATE TABLE stage.mortes
(
  ESTADO VARCHAR(250)
, PAIS VARCHAR(250)
, LATITUDE VARCHAR(20)
, LONGITUDE VARCHAR(20)
, DATA DATE
, QTD_MORTES_ACUMULADAS INT
)
GO


CREATE TABLE stage.recuperados
(
  ESTADO VARCHAR(250)
, PAIS VARCHAR(250)
, LATITUDE VARCHAR(20)
, LONGITUDE VARCHAR(20)
, DATA DATE
, QTD_RECUPERADOS_ACUMULADOS INT
)
GO